apiVersion: v1
kind: ConfigMap
metadata:
  name: trino-catalog
data:
{{ (tpl (.Files.Glob "configs/*").AsConfig . ) | indent 2 }}
#  tpch.properties: |
#    connector.name=tpch
#    tpch.splits-per-node=4
#  tpcds.properties: |
#    connector.name=tpcds
#    tpcds.splits-per-node=4
#{{- range $catalogName, $catalogProperties := .Values.additionalCatalogs }}
#  {{ $catalogName }}.properties: |
#    {{- $catalogProperties | nindent 4 }}
#{{- end }}


